import Login from './Login/Login.jsx'
import Home from './Home/Home.jsx'
import Header from './Header/Header.jsx'
import Register from './Registration/Register.jsx'
import Device from './Device/Device.jsx'
import AddDevice from './Device/AddDevice.jsx'
import Footer from './Footer/Footer.jsx'
import GitHub from './Github/Github.jsx'
import MapComponent from './MapComponent/MapComponent.jsx'
import EditDevice from './Device/editDevice.jsx'
import ContactDeveloper from './Contact/ContactDeveloper.jsx'
import Profile from './Profile/Profile.jsx'
import EditProfile from './EditProfile/EditProfile.jsx'
import ForgotPassword from './ForgotPassword/ForgotPassword.jsx'

export {Header,ContactDeveloper,Home,Login,Register,ForgotPassword,Profile,EditProfile,Device,AddDevice,EditDevice,GitHub,MapComponent,Footer}
